sudo: required
servies:
  - docker

before_install:
  - docker build -t devang14/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true devang14/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket-name: "elasticbeanstalk-us-east-1-918666471493"
  bucket-path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY