FROM node:alpine

WORKDIR '/home/node/frontend'
COPY --chown=node:node package.json .
#RUN chown -R node: /app
#USER node
RUN npm  install
#RUN chown -R node: /app
#COPY . .
COPY  --chown=node:node . .

CMD ["npm","run","start"]

